---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: baywatch
spec:
  encryptedData:
    root-password: AgAeDFV5yOZdU1y4pR289SLjAR95tVisrFFz8/RvCSWLEu2JRDlv6SwZnLU3dJQPGpLqNCAFIw/W0ljYjwkP4RXh5LWyHyUXcQZ5S9zkw1LWbxfNjiWI3hN/JSHDULFZRKUOmNYyq5Hg/XoZ+SbofH6O6Vxred/LdyQKPI+OKN5Mmf0IVJ0R8tSS6tnVk2ldx39DG7YJ4GjsviLkJVDgoPRQ7/Fvzk1yRxgaDB1XaHJZSPc+aKj+n9oPaoZT8CVFepKl5DHcN6Pqwgajq1DkbtIiP+9qEXIQUWX9ERU+Crr5oMXu6UNB4XiUJnfUc4/3dO5t4FTPeo64qdb1CKh2qfKrN3c03lyzzPqw8R3yGMqmArwBvL2x9i+gs7aHRRM2QMGF8aIk3V3TxYjMlzBqPqCh3gr8qYqzAqywAhGofqfAi+t90vWWkMBrb8RcG+KlU3Fm9JTQmuoQXN/sHZ77YI7GUUz8nBMzp4tDwbr3sT+U6JOfAhIy1ZNXc6Bz/D3kEff7qAazl4hW2bjmPWcP9xWB8z5/tTpOSceQKmIFCIJ0PUfevJN2sYqANU+UqBFq5qhKMBlFD0oPZs70gP4m8DbAsaVgQZbW41Sit5inpsG8EWkn5FWOFDeJ4Johh5irjuWV6B9Gtx2ezhNcTbg0i5j1VRaq0BrQgjE49ooRWW0kWwjbgl/Sl5bCt+9pzsOE2WK+F6RdsB8/LsxLU0oKCU4+eroVtOfexjuRY7sYfwXL0Q==
    root-user: AgCkEbJww8rZJD45SapEBVtPLZY99mzTayh9CLfLoeFz0otldk8TMCWWDGoeAfXsQglUJriOQo+9iiuAlDVLXzUdC4kyM8YAKdCTmMBDyIdJVZQiMLDq8s90NrTMMskc6hTP525d17Wbp9yiXf765L+TSdKWvzoKE5gzsp8+ysJ0JREyl0XouyA0cDs1c0TIewbaaFRj4Bk2ndUy//XGfr9LFf5tE/4wLRHNKzWjnGXvzmRH/r5HnylBFdy9qV/yivS392MnYZe3A5Vk6DAus27UK+jS9Knz14GAldIMz+xPfzrsemPYCmSSXrSdavUzVfwMCTUmgyeQZENc7yBi78RikMJMa6YjDdY6u9WzqthufZJwYO6cToRIphQSsa7Er8DPmZho4diFDF8CIllHksSlxa+10fY8ZPN9aMwFCqroK7I6h/2rVUgA/nihxWk2uWuX2vsQryDGW/WdUhp4GwhWXFxNxuLGTiXxQn+/1+iZi08KbJ4rOd1SgINqgHm0AYQgA64L7FIyWBI6YhpOlgP30VB/OUm5DzrdzpCPF5STf0cVplkyyuvj9BWVpvHy6CFZc0SigAyImfwTgIETIWUwG8waFmSTAk+RYrwu9LAWcwTIyvEYHLoImjg86FuNv/wvrH47Z5FNr3b+zSvj01W3n9DGwWt2r7C4NTPKDnS1qa7kM//i/qF4iSOW5gfla+uCb/Mr0+zJQi219r3meg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: baywatch
    type: Opaque
