---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: baywatch-postgres-credentials
  namespace: baywatch
spec:
  encryptedData:
    password: AgAQFLmov2MELOysRDqZGf+kGZL7AWDjWpkEndM1nAdjoGKwzoqtHJrhze0JbzuzQkmhEKnQ6jae1iEVc2gyZYNrkHX53gw2Qqn1qjxbhtYxBQQ14cKviUmifKC3yZJq2ffcuJywTj1n1CAGyKjSPUr9VDpb2uuDTCn3LdGRvNEVhy5uyHd0k6xpgCFvqlztNNw7vprLc6JwiUhWYvCu0nOMny1hxx8JVesLlKl9d2fWyE2IPBJjMYPdnPlj7ZuTvO6054By5Uhuhw9MgGek9ATkOVOdbY+NyQuQfqRwkaN/2KawbnpejXw2q01If1BVCB3k23ezaj9jllvkuAM6sS6iaXKiDGl0WdHTe9SUL0h1IO8pNU1sHk4JMyit4dI0lOLlF/8tuf+qv+SjOiJuRItvm1XqEtqCUZ+lE8s8fKg8M6RbB8YAGJog3geqEQjKmihi47q8KNVyptqoiNlOiqJGhkJrHB53GcN88Pl0zgLrnf2FHcSnD15KBnyXieoi5uOlG4+VYF3P7/RSAyiSw+ZiSkSzS06S7wS60frERUuyMI0xngYUrRmJlyjC/XPt6haik6yfUuUi1EwHXPFmypWlQ/jQOASP6VfykWIvWWktknZGxDaXaBcOrA5ZJtdU9EJW9ps5thjyNi7debbe8ORn6SlWRM/rlQIC65WJw2uGIh8LuWtJfKv64MFqPFbRmgS2tiSL3My7jrFzGiZQs76DKkKxQUmXfwWLPlanUHWW
    username: AgBWIkWL71GzHFnZ2W9ll0jpmtQdj530wECsFYg6J6JMvEJvPiLr6gczHYspiWxfiTuAD85ZiSXCuAS2VY3Er2UfAGADz7R4RumvtsDkSu4xMXZESI+Wm/d0XarY0k9+uuYLVJ31BwBRfRUJf8hVeFKJJIkKD/q6tkNTPJ5OBFnGcvJ3TA96PRDAfX8KqL5vyew1fGdLyAtVcPJzUXXfMRCgzH6Y05Ij63ZgJWPgpLNg6lykjuZGVmGqkyH1DBhIoIatIR9fDzzisW3EDZL8jNK3Q7SWr4UwmlGXXbn2cNoLzeeGIuMPHfOjcMqs3rlBAXsPlaFUYMrbZjfteAVsEIt0eeuxo5hBP7BSVzSmIsOQEaci6kU0mYt+xsPnPfsYZcZBdczV0H7j6pzgzhPtgDlSerBktX/2Van8oakDH5CjkZvHrgBugvcGWmiCyvlQ93ozY8hYr2RwkT46kHl+SN6plvGlJ/6BzhhvU9beQjmVOVenMMBXPZU/XlvtoXoCMW645xd3EhPIZz8tyOnNG5xkg0fkvtT2r0orRasO7y5iQVVxL4K9zchG/41nYtm8mWwTp4p/E6oLG2EyjGjN1xCludAiUhIY3GQQUzPqEBFSuWWXhWAILtFJbiEokMuH5t0Ep7Zmfhr56om9I5XjIFzUF7inp5Lqm/3n9GXI2GmxTKtQR1ZCom46R5aMXUVDOgxzmKxesKCj8w==
  template:
    metadata:
      creationTimestamp: null
      name: baywatch-postgres-credentials
      namespace: baywatch
    type: kubernetes.io/basic-auth
