apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: ">=1.82.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 12h
  releaseName: tailscale-operator
  values:
    oauth:
      clientId:
        valueFrom:
          secretKeyRef:
            name: operator-oauth
            key: client_id
      clientSecret:
        valueFrom:
          secretKeyRef:
            name: operator-oauth
            key: client_secret
    operatorConfig:
      defaultTags: "tag:k8s-operator"
      logging: "info"
    proxyConfig:
      defaultTags: "tag:k8s"
    apiServerProxyConfig:
      mode: "noauth"
