apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: ">=1.82.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 12h
  releaseName: tailscale-operator
  valuesFrom:
    - kind: Secret
      name: operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
  values:
    operatorConfig:
      defaultTags: "tag:k8s-operator"
      logging: "info"
    proxyConfig:
      defaultTags: "tag:k8s"
    apiServerProxyConfig:
      mode: "noauth"
