apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-sample-pooler-ro
  namespace: postgres-sample
spec:
  cluster:
    name: postgres-sample

  # Use read-only pooler type
  type: ro

  # Create 2 replicas for high availability
  instances: 2

  # Setup monitoring
  monitoring:
    enablePodMonitor: true

  pgbouncer:
    poolMode: session
    parameters:
      default_pool_size: "30"
      max_client_conn: "150"
