apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-sample-pooler-ro
  namespace: postgres-sample
spec:
  cluster:
    name: postgres-sample

  # Use PgBouncer implementation
  type: pgbouncer

  # Create 2 replicas for high availability
  instances: 2

  # Setup monitoring
  monitoring:
    enablePodMonitor: true

  # Read-only connection pooler (connects to replicas)
  role: readonly
  pgbouncer:
    poolMode: session
    parameters:
      default_pool_size: "30"
      max_client_conn: "150"
