---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: marketmap
spec:
  encryptedData:
    root-password: AgCy7VMWVEjf8aHkDEH0n5EpuZLGBwys316OP8oz6nir9HKOFQWZqWQW0hdnDCUZgEiKMOlCvdzNv7lMnhxjKwJJpLU8Ln7lXHCpmOiHEBumEmEYK18GxK7s38cTfvnZt4UoFjscXuYT2Epre0wUQzqnhumqryb8Av+RgBK9VHL/HaKe6L/h6bWUJ4sJtEDlaL/DmVpTcZYtK+sGrCj53JM3S4lJTkds/eNeOkyxvUbhewF8hGdlfzTr3w+jyBiG/2ZFVDXfUpjpbz0+gsYZZf5SlnwFobTmdcDNIiktQiVY4/cU8H9oU8WhEu5OOFXotM6e5uiHAm7ad3aq6A0r8eskg3NNgHXVwqf5js9huOOZwKjoF+A065i1pnWg9mSTXBrDfrAkNZrAFTQ4WALKIdNe0uEoDVjm4P+oA7pH6INI5e8OciBH8hHOpaile/3CfIFwvBANEwcnG2B9ozHcq5zKpk1mYo36hX0FGnsr7RRUIFMXhg9VYbZkGjLJ4YuA6oSK/yq/TgwroXCYF+L2edR5riG7yUkGdFLELOdsCO3IDsqUq6aaEIAlhqWSTgBzL9isx3mec8ceyX8HTF4ITR6L2x2/9rbY7lSH0hjrSvFtbYhf6qPXE3z+4eZGkHZi4+AaIxvkZk42RVKVS+uYf597TrLXsIz15R7ekyGVTm5RRll8VH8BDyDaDcdcOMEN2yHLyJRayxeaq7YjncST23HYnfyivwmX67Fr8/Kr/kaboaCqOCBiVqKh+P1pznqPGkA=
    root-user: AgA1+CRde7BJn/V6Z8IlwWhie1+1knGNTyGCI56Tkr4IIfQJWLXxBIpNy8BCWtXcRV/qjDs3RSPjwTBSIxpXqnrwfl9OGKENuawer6iFYVSdSSfNnNoqD3l0cjIuvQdvQEZ/sdXdmpjjtC3qczW/5st+XyXOYvispFgROtB/R5NMyiQk07bilAiYy9uvB7BS3fsI/PPsV2dBVqqUaENNOKd+9T7CVbppCUbUjZ4Q8YQpPskfwSPgTHGzDh80KKD1XIC2XFxZ64RxVNg0UEAiq1J1LZBAQe8rt8Us5eZMIecoWoX+e+soy3jk3EvISqEmJbxfp83rzBO0rn3ItUHVRdR0jkvlNW6h2IxStXbtMzCGT7g2buiBJwfnsXYCtz7ZA2f56hJb6wcVYjkoKeB62BjTluhWL1lawbfw8ozP1McFujOVlwb9dWtTh0UIERzQkGEF0KaEMM2aDVVhtxKi8pm86gbSZg+moj68rAjYm8QBdJLC3dTo28Pb7hrZ/oiWxAJVdbA2gCxW+s7pw/NMKw2+PHB9N+dA6EhwGGgP0BUwcNQgf39hYKCfpWRalyYb3LDBOjmlmVY3INR9LGX3FONu7AB6F3swtb/Fa6nhWQGg6e2ZxiYsQpe9PqfrqN9Wuvy0HAd4L1jlnNsPt1R+G70WjYK+wd0X4OtJCsBZmB/S2F1prJCOCP79MZmrEoVcxVQcwnTdrrrB0Gj4sWLgsw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: marketmap
    type: Opaque
