---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: marketmap-postgres-credentials
  namespace: marketmap
spec:
  encryptedData:
    password: AgBaxM/FYOqNHQRZ70fuPAETqNZzQ8cZjaAs5g/HNhtsxQfQMozBrA1GbjtDPHcoEdvnofGJCQKIZo/CZqGEwnCVGP00MYmaeRxKAQdWrAszGkS9ooxAt5iQyCVnvYmO6j/fRWpZZ6GFvZ1jrwSf5lcWU8UMYAn/n5e/Py+yANjLQ6Z4+YqWIHfETiVNc3+Ifu75w7xzUihInUmFw9HseN6zZfIyCHTH1Pvb+jWkIYLDna7dVE5d5HHfeHqmGAruRNJELMnFGhKpwgftjgpyM1FKZnFBI4HrIYdtepvg8AzqkF2yH1IlZFZ4GsPWWclVfU1BXvvPSiDKgE0BlWa+0RwILzdawSF7eHHVI9GV0buGVps39xHLz8KPBFEsiJ1zxfrVPyfQwCjz9GKArazXSRNN7J9Iyh+hFZ0QMxw0AV4VN2iscGvKm4EsBqYX/oaRtmv4NhwZ33XuvyUFW+KZKiA/jTovIFwUti42uJmOoWOCdLVZoxyeO/47J+nfoiyWZMGRDLNEFgIOGqd4nRqt9NUGJscIz+gDguIGt9kf6PTVsfmRmcdnwWh+oWeNdwXQUFsrmGzCtElUy6n1xTwj/tgDyQpAp4jg4nT6B7abxM90KgnkoOcG8heGb47BoxSSBf6P5TYegPXKXLAimH5HlKtEUoAlqTZWAFyTaWGj1p6lWWVGosaiy/BBmE/aV2WFK2mWHeSv/YJXWG8YaHWcFjjiFDb3Qr6GczLtQ1zvPxJejfi2xxc4OrrDV5baXyyykbw=
    username: AgBANxdV8SnzcRudFi/xk72L3k0dsTq7KeVY7RgYvFJhKjFO03HKK5FxYW6ajNGkik8N9ze0C71BrbTO/tUUIrXWQdRhtrshvjaM3iPgOCI11+Dl5jUBwkRidj01QWe/hhxB0Tpqtz5dJgDElu9964i7R8IDb1VvGg5IME9bk5KuZaCQ53ko54Nt2lJSE6vlXRI+dcTMw5oUc/0qffdS70O+t4MI1tngWtkGhNtNCRfQYKn1+sZY26WMKzLPfTsqbsf7/fQPaKTMM9QQMpoEOIGVqOvHELcMB/IO8dQdNzUgVYjuSFqSBXFyNYti/MuiyCyWphpnU+ZkP5DYLxi/mqK428BI67mmWeIP04nOiytyK7kjM9jHTR8Z0/AvNobVxKZvdrm+1yeALxClmQIdXv6Qg2SyqWUgqepIbIOhojvxkHtBNCkJ1eMgBgDRqadHPj2XveqwfT3YvEgtNc5lrvN6kapXNaE72WL0SrAwBW9onuqauxcuHP5YSw+DNkEz5Wxyan+IpPGldgblXPkh/w4sjASkwtYwyHA6d1DiDYww8z9U9WqS2xOlTbKGajZV3ijfUqENM9X0nbW89KmHfV0BQBuXZ9g+R7nBjal2d4Qo/gnpuo/M/CN6ZilC3qBJ2jDThG2lSpKgfyeo4P/WRye4QMQwdWCvvyWBOnjx3r3keVgi6YOH0M3v0dvuE+cPJyk4RMZSTV8L/YI=
  template:
    metadata:
      creationTimestamp: null
      name: marketmap-postgres-credentials
      namespace: marketmap
    type: kubernetes.io/basic-auth
