apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: cloudnativepg-system
spec:
  interval: 1h
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.23.2"
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    monitoring:
      enablePodMonitor: true
      # Enable ServiceMonitor for Prometheus Operator
      enableServiceMonitor: true
    # Enhanced resource settings based on cluster scale
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    # Additional configuration options
    config:
      # Enhance webhook security with cert-manager
      webhookCertificateDir: "/tmp/k8s-webhook-server/serving-certs"
      # Set to false by default for better compatibility
      inheritNamespace: false
    # Pod security context for enhanced security
    podSecurityContext:
      runAsNonRoot: true
      fsGroup: 65534
