apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release.yaml

  # StorageClass parameters are immutable once created. Applying this manifest causes K8s errors.
  # Commented out after initial creation to prevent Flux reconciliation failures.
  # - storageclass.yaml

  - ingress.yaml
