---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: steel-gateway-secrets
  namespace: steel
spec:
  encryptedData:
    STEEL_API_KEYS: AgBSaOnCD4l/rkSgSgog3hhwJhx7P/CAXltEsLI6Pyb64RsHw1i72IyxNCb+uHGNg0WOc4zUNsBxqvQmeijpmpgYTH6xI4y0jJFzY9pN+h7Jy99Dc6G33QGRcpaoENZ6X0DnkddtFImWCZi5+86hf1pYnys52BAjSpgm1427lYSFElLlf1hLoeCzxaqvVUOiGAWbg6oyUMq7hF+aICxNu2TnNS+YXUbysvYjuaXUVuxcMCHVXquyVTMxJgWm8EIkjgIzXMTDQinElvYQCFI0jlM9FYn+1fBq0K5XEWIq+fCdMH/TUcT+F7/TSANLShqdGJk5bxGfJpfgiefPZj1dtn2S+pkNpQRu1h/jvUzv/8YgFHccGOz7uDl70Zb0gzhUS5gfohV0l6RhPEu0wNKCdyZhhUeFuVMGnbPFIELfvW7x00nsV834ZaoXSp8Zg14V9qbNqcSRLP/6J38hQAGtON6HIFx1VExq38abh+SPo9x0mjApT8rRQvopAHQQlwqA8asEPJEOqTDTGMMm26wRy0vTnS1J9tcaq3GNLBRFGHITrxPwtUG5csdZnpi6DtIRawfM33B/zk1TV5oLyyCyrWT9bjMqqgkH4V+BOdIBliWYU+mPdHPLe6DR0izxtEjFOKyh1qoCvCFxFoOahmoLVK3UreZO3aONy/LqVaDUcyFWoHt/6y0svFzCX20hWqAsuI6Bg6ds4sQ4PsN+wZhwR+07UdeenpOOZtGbfZ8eGcmcm8qAF9JrQ5N92XooKmwECKemZ9LRXKHDs534kCJc+5J2Vq6kR6Xk7vBJIlUTOQMFTRxi+Tf9wzg3Yd8d6HZkVPnX87GDPx/BTGfdzDe8QhWCszZG4CyxsV1Bv/qCFz9sBOK4STdpoI0G76y4FrneCoKYAzk8sRhVfHJUr+nZ7rgH0oYRi2UxwI42ZF8dyAbf3EspQwk=
  template:
    metadata:
      creationTimestamp: null
      name: steel-gateway-secrets
      namespace: steel
    type: Opaque
