apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: docker-registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: Registry Realm
        path: /auth/htpasswd
    maintenance:
      uploadpurging:
        enabled: true
        age: 168h
        interval: 24h
        dryrun: false
  cleanup.sh: |
    #!/bin/sh
    set -e

    # Garbage collect registry
    registry garbage-collect --delete-untagged /etc/docker/registry/config.yml

    echo "Registry garbage collection completed"
