apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - registry-storage.yaml
  - garbage-collection.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml
  - cleanup-cronjob.yaml
  - registry-auth.sealed.yaml
