apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steel-cache
  namespace: steel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-single-replica
