---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: landscout-postgres-credentials
  namespace: landscout
spec:
  encryptedData:
    password: AgCHiM6hpmfpWexDFh4e1+75MVXPcxygIz1pZcYS7wl97XZQRbgjsqKXFnQMOkuWM5WL12/20JoGAmnwNK9Nv+giTnKx88rczB1H/DY9g/i0Ckj5F9Awo99eACxQ/Y3UiQ1OtiAANVKHB3vR92lRmAXDjqEPhnlgS/IrelyOwbw/+kVJVbQh/1B1V+sZNO1RC5tI0ktcdRECctwEsTkf0IFHrxhCE7QofQBkO9wy6U4gl4Zl8DbR0+aY2aGJocl32qz1zrRZO7o8yvyDrjUcyfQUlGi34qejSW7ISdfhgiLakpB+huGp3maB1dlgG2HlKKqMNNdlZT4a1HlPu6eg8VB5a7rjxEiteZrxWiRykHmTsm4NHqPgYX1RR4dhMc7Fn2nEnmmNkVt9SjYhjN3ghJNTB7JVo+zuzbZg6JQV+gqh0GpvsKecX53T+3Mxy262gAmh7AqFKf7JijrEY1gPZ/N3S7RerUHJ23u5VjUmj3hsJiuN/qoAQYluz4b4jy33abKmFtyA0Txq7IE2cQtrFWDAxFDPmcFkP5SGlGk72W8fb+/VdEUTK/UebgBBZD9hDdHKY3ciqHqmv1Iz93OfMuetWFEe8C1TMWSLYKODquPzTDicpiHoHltvRbjYTItIkfmwXyLzWVp0fSq9JbOaCr5AaHUYE4hdNlaOgm5ZWSAQut5nY70n8KLYW+jkj/D/uWtLPlt9D2GohLjKPfcwuZh50Jcd9yf7/2h64EgGedhynA==
    username: AgAmUIbyl5SfkBG+f8DEha6ex0iTKpAJVMYve1BkloEP9IuLVojkNFI6f8hNDmeP1kbRLu1dLKPrpoL5nz46BFWaf50AJGfItLmjy9FzQ7Txgnm8dRW1UeejsAXN+egQ7GSIGxNe5z8W5ncTUymCGY5QXrzl4fQy2TEZHc7+J7r+yBFRuaeaDZmbjQ/9UJkyjjoRqVec8rIF9JAeek3Lg2NDBU+RPuO0QX3l/zKjdrLkiD5XP6n0s4vA3uEzCtwo3x04c407zuRpDuo4aDGg2SPU6Pc/bEM/2NsbXeyFmQJMXfw9jrwQ70SaO/6VPBWahcbXItwn1EHgQYIJkq3WaTx3LslnttmSh+PpSH5eoMIsSxmL2de2CScp3hpw8I4InBE1uBhbn8itKNeTPsScBiNQFfAwrdA2sEJ/1vrzzdceGFALDtHMYOk/EZngSaY+vED7wrR3PjbpO4ecMAhkBIgODulHFzNK8BzrY0X8tT6coqHyWWnd+evwm5xQhenhUzVQIsj8XJONCJ3vfT9Ti/04JwubIrdP8SmnxLmvfA2WrKW3zp0d/FpRWyWPJhIpPEVqxx4cAUS8uascfbteuqo+bbyUVbB7xhi+hfAU0e41gzRG7ElH33L4Wg7iAwdT71njNvYQn2ULnu6sac1Lg2beqB7+haRB1vc9wKgWgOsEfvJYnZHcU0sNXFcrCUyteTcpH//kBJ7OewQ=
  template:
    metadata:
      creationTimestamp: null
      name: landscout-postgres-credentials
      namespace: landscout
    type: kubernetes.io/basic-auth
