apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-User: "{{ .Request.Headers.X-Auth-Request-User }}"
      X-Email: "{{ .Request.Headers.X-Auth-Request-Email }}"
