apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: traefik
spec:
  headers:
    customRequestHeaders:
      X-User: "%%X-Auth-Request-User%%"
      X-Email: "%%X-Auth-Request-Email%%"
