apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
    trustForwardHeader: true
    authRequestHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-Proto"
      - "X-Forwarded-Uri"
      - "X-Forwarded-For"
      - "CF-Connecting-IP"
      - "CF-Ray"
      - "CF-Visitor"
      - "CF-IPCountry"
      - "User-Agent"
      - "Accept"
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Location
