apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "35.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
          options: "default"
      postgres:
        port: 5432
        exposedPort: 5432
        protocol: TCP
    service:
      enabled: true
      type: ClusterIP
    # Expose the postgres entrypoint on the Service
    # Helm chart expects a map under ports.<name>.expose
    # with keys like `default: true`
    ports:
      postgres:
        expose:
          default: true
    tlsOptions:
      default:
        sniStrict: false
        minVersion: VersionTLS12
    experimental:
      plugins:
        htransformation:
          moduleName: "github.com/tomMoulard/htransformation"
          version: "v0.3.3"
