apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: t3code
  namespace: t3code
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`t3code.nmajor.net`)
      kind: Rule
      services:
        - name: t3code
          port: 80
  tls: {}
