apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocodb
  namespace: nocodb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nocodb.nmajor.net`)
      kind: Rule
      services:
        - name: nocodb
          port: 80
      middlewares:
        - name: oauth2-auth
          namespace: traefik
        - name: header-transform
          namespace: traefik
  tls: {}
