apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - postgres-credentials.sealed.yaml
  - postgres-pooler.yaml
  - nocodb-secrets.sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
