apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: nocodb-postgres-pooler
  namespace: nocodb
spec:
  cluster:
    name: nocodb-postgres

  instances: 2
  type: rw

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "100"
      default_pool_size: "20"
      server_reset_query: "DISCARD ALL"
      server_check_query: "SELECT 1"
      server_check_delay: "30"

  monitoring:
    enablePodMonitor: true
