apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nocodb-postgres
  namespace: nocodb
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi
    storageClass: longhorn-single-replica

  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      work_mem: "4MB"
      maintenance_work_mem: "32MB"
      effective_cache_size: "512MB"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      max_worker_processes: "4"
      max_parallel_workers: "2"
      max_parallel_workers_per_gather: "1"

  replicationSlots:
    highAvailability:
      enabled: true

  bootstrap:
    initdb:
      database: nocodb
      owner: nocodb
      secret:
        name: nocodb-postgres-credentials
