---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    tunnel-credentials.json: AgBut0sAl43qFd7GeaEM9Ud37BXdWTnaViBTQtw32gLVqLSm18QXZTkTyKLHbP5YdWhvwHHcOwZaapzDyF9PfqaHWFv9SK71sj1StT4tD5wg1YM5isbcRPGcY2SimULug9Bzsdh5xLDbu1MCtFyD1dP3uy6WfZSp8eGTBo6F5lz+tMZf7PmmUBch5p9ridmrSExXFu3OgsBXNDeT5d3bTkPiI8xGhELqKQmQeIWD6gJDi9wU5CpOv5WladFBgh6MBK4dFXydxrMfMflQMuOUILNd4VyZPYq0n6UzSeMBBdtED87lg8OdAzPnhEN3oaA2vkBjNxaPMUYgzwmYjbHULGniqtRHJoAGGfJdEFauxCJd9f6yA/m3uoTcxMftCxLyuhZu1aXiskplsz5FIpVA7m1Y4H6ez/E0aBAvh5VXYfCZarFEi6v8LAo6wg2DhBbiYnIGxB5aNMcvK2XpqnUhW2YetOGXG1KStkG0F7L1aNSp/6mvV7gKl/QrOBrYg+xLzF808QqQ+q6sBZm9bcD5ETkXQT5Q8Gv2PF9LfufpXGo0Ij509oQpGctZS6W1OCy06oXI2AEZyWkJYdltY/0m+V7QGMmJeSCLYoDyW/z8s53E7z+BiFMu8sbLcKFJy7bINZqAhfRIGU3qNxF2qxAfQ3iOraWX9FV/iPMFj/BQr9dCMNMgfh68cZocMu0HsdM+gVKc58GnfwUFMEaYtaCJ5mHTppKdULsSAbhuGpFiD4WwhgXkHjtxnY8m+F/iwqLCOHHDlLlVwTT7HLSryRbWOsWkLrYCnmCN8iikKsx3cKvnwewCRu9pPCR4bCzsdqvwkxLOFeTKCThBRgjxYljsDGaqvBGGGwxQxa/PqkognIBaTd6qbJwJDOD+bbonC+QW/13mEO8hjPM4udEpcIizu9QTh6U2nW0KBGOMsf8simJhFbq1edK4T+L6e09V9Q==
    tunnel-id: AgAbBJ793Ci3k7AMyi1fOMPAtikS+reydD0JOecDN0zlrTF7VMGeplAY1Qbsu/Ck3PPhoLiARl84IstgmjJ30kyfKX5xGn0QXG+VtyRFqwdbGe4MoQuU19A8SfyLLScRYLnyUcxEv1M5v4IOLWD/1a5FezFmj5CxXvZ/WufCIiE5rtE5hCEC3A5kfDf6NrhcZOAcD9fLN2ROnm+VcFnTLI3aO0fjXljtr6PlPNwXcxJqXGnAu8tqv0MYcE5TXvmT/+OsVdvICm/Bn8zwuv0TbPuOk63EC32c/c2akcCdsLYO9G120TVfxhk4cIvY3OEOrFtLnG7iHMtfdzpBuFYoIysffREqqO052A/E6NCj6QOt9ETVbDMkTZJKqIBOq60rdMOeRFG9TN8lVfgl+RnZ2t7zzGIMNp5h5MTJfTtnNNBwVWQPZZYIVf9Dc6fosykIML+ud9zao4H8J8fdoQ/6rIQ/z5i+HKROEHvNZeYEzP9qXTb6ZswFJuxnxqRIlViM3lr2AEIDRcHD4xfuQJz+np5bNFOGxbjLf0d4MrXNL+4Of+fsXm2r0vxvEFfV7rEnSF9ldzY4Kydm2GMkSCSPDYhgu7sHjs7BEUBS31VwKQTNRA8VpWU2XZK2kJuGzNnbpxJCDezJB/9aNpvtNdXztap2ivDhp7Ay9H9e5rXZVaCQTgDp4G6+GV/h5pCpD3jR0jo2PT7PDSd65xPgE8UbRdpPwY3WCjZMFk3y9b6Y5+T4eJmAscI=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
    type: Opaque
