apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # This YAML section maps traffic from hostnames to local services
    ingress:
      # Catch-all rule to forward all traffic to Traefik
      - service: https://traefik.traefik.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
