apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: ${TUNNEL_ID}
    credentials-file: /etc/cloudflared/tunnel-credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    # This YAML section maps traffic from hostnames to local services
    ingress:
      - hostname: echo.nmajor.net
        service: https://traefik.traefik.svc.cluster.local
        originRequest:
          originServerName: echo.hlkube.local
      # Catch-all rule, which just responds with 404 if traffic doesn't match any of
      # the earlier rules
      - service: http_status:404
