apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2025.4.0
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config.yaml
            - --credentials-file
            - /etc/cloudflared/tunnel-credentials.json
            - run
            - $(TUNNEL_ID)
          env:
            - name: TUNNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflared-credentials
                  key: tunnel-id
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - name: credentials
              mountPath: /etc/cloudflared/tunnel-credentials.json
              subPath: tunnel-credentials.json
            - name: config
              mountPath: /etc/cloudflared/config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: credentials
          secret:
            secretName: cloudflared-credentials
            items:
              - key: tunnel-credentials.json
                path: tunnel-credentials.json
        - name: config
          configMap:
            name: cloudflared-config
            items:
              - key: config.yaml
                path: config.yaml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cloudflared
                topologyKey: kubernetes.io/hostname
