apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.12.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    config:
      existingSecret: github-oauth
      cookieName: "_oauth2_proxy"

    configExistingSecret: github-oauth

    extraArgs:
      provider: github
      email-domain: "*"
      github-user: "nmajor"
      cookie-domain: .nmajor.net
      whitelist-domain: .nmajor.net
      cookie-secure: true
      cookie-httponly: true
      cookie-samesite: lax
      pass-access-token: false
      set-authorization-header: false
      skip-provider-button: true
      upstream: "static://200"
      http-address: "0.0.0.0:4180"
      reverse-proxy: true
      redirect-url: "https://auth.nmajor.net/oauth2/callback"
      real-client-ip-header: "cf-connecting-ip"
      standard-logging: true
      auth-logging: true
      request-logging: true
      silence-ping-logging: true
      cookie-csrf-per-request: false
      set-xauthrequest: true
      session-cookie-minimal: true
      cookie-refresh: "168h"
      cookie-expire: "168h"
      show-debug-on-error: true
      insecure-oidc-allow-unverified-email: true
      insecure-oidc-skip-issuer-verification: true
      session-store-type: "cookie"
      pass-basic-auth: false

    service:
      portNumber: 80
      targetPort: 4180

    proxyVarsAsSecrets: true

    sessionStorage:
      type: cookie

    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /
      pathType: Prefix
      hosts:
        - auth.nmajor.net

    metrics:
      enabled: true

    livenessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 5

    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
