apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.12.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1

    config:
      existingSecret: github-oauth
      cookieName: "_oauth2_proxy"

    configExistingSecret: github-oauth

    extraArgs:
      provider: github
      email-domain: "*"
      github-user: "nmajor"
      cookie-domain: .nmajor.net
      whitelist-domain: .nmajor.net
      cookie-refresh: "60m"
      cookie-secure: "true"
      cookie-httponly: "true"
      cookie-samesite: "lax"
      pass-access-token: "true"
      set-authorization-header: "true"
      skip-provider-button: "true"
      upstream: "file:///dev/null"
      redirect-url: "https://auth.nmajor.net/oauth2/callback"
      oidc-issuer-url: ""
      skip-jwt-bearer-tokens: "true"
      skip-auth-route: "/oauth2/callback"
      standard-logging: "true"
      auth-logging: "true"
      request-logging: "true"

    proxyVarsAsSecrets: true

    sessionStorage:
      type: cookie

    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      path: /
      pathType: Prefix
      hosts:
        - auth.nmajor.net

    metrics:
      enabled: true

    livenessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 0
      timeoutSeconds: 5

    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
