apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    # Disable Local Storage engines as we only want Mayastor
    lvm-localpv:
      enabled: false
    zfs-localpv:
      enabled: false
    localpv:
      enabled: false
    # Configure Mayastor
    engines:
      replicated:
        mayastor:
          enabled: true
          io_engines:
            additionalArgs: ["--iova-mode=pa", "--env-context=--iova-mode=pa"]
            resources:
              limits:
                hugepages-2Mi: 1024Mi
              requests:
                hugepages-2Mi: 1024Mi
          mayastor_csi:
            node:
              kubeletDir: /var/lib/kubelet
