apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-3-replicas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: io.openebs.csi-mayastor
parameters:
  repl: "3"
  protocol: "nvmf"
volumeBindingMode: Immediate
allowVolumeExpansion: true
