apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.nmajor.net`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
      middlewares:
        - name: oauth2-auth
          namespace: traefik
        - name: grafana-auth-headers
          namespace: monitoring
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-auth-headers
  namespace: monitoring
spec:
  headers:
    customRequestHeaders:
      X-User: "{{ .Request.Headers.X-Auth-Request-User }}"
      X-Email: "{{ .Request.Headers.X-Auth-Request-Email }}"
