apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=55.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        configReloaders: true
        general: true
        k8s: true
        kubeApiserverAvailability: true
        kubePrometheusNodeRecording: true
        kubeScheduler: true
        kubeStateMetrics: true
        kubelet: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true

    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["alertname", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: "null"
          routes:
            - match:
                alertname: Watchdog
              receiver: "null"
        receivers:
          - name: "null"

    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: browser
      adminPassword: admin
      service:
        type: ClusterIP
      ingress:
        enabled: false
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      env:
        GF_AUTH_PROXY_ENABLED: "true"
        GF_AUTH_PROXY_HEADER_NAME: "X-Auth-Request-Email"
        GF_AUTH_PROXY_HEADER_PROPERTY: "email"
        GF_AUTH_PROXY_HEADERS: "Name:X-Auth-Request-User"
        GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
        GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "false"
        GF_AUTH_PROXY_SYNC_TTL: "60"
        GF_AUTH_DISABLE_LOGIN_FORM: "true"
        GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
        GF_AUTH_OAUTH_AUTO_LOGIN: "true"
        GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.nmajor.net/oauth2/sign_out"
        GF_USERS_AUTO_ASSIGN_ORG: "true"
        GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Admin"
        GF_USERS_ALLOW_SIGN_UP: "false"
        GF_SECURITY_ALLOW_EMBEDDING: "true"
        GF_SERVER_ROOT_URL: "https://grafana.nmajor.net"
        GF_SERVER_DOMAIN: "grafana.nmajor.net"

    kubeStateMetrics:
      enabled: true

    nodeExporter:
      enabled: true

    prometheusOperator:
      enabled: true
      admissionWebhooks:
        enabled: true
        failurePolicy: Ignore

    prometheus:
      enabled: true
      prometheusSpec:
        retention: 10d
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
