apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: ">=0.23.0"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  values:
    authSecret:
      create: false
      name: controller-manager
    githubWebhookServer:
      enabled: true
      service:
        type: ClusterIP
    metrics:
      serviceMonitor:
        enabled: false
