apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: private-repo-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: nmajor/hlkube
      # Labels that will be used in GitHub workflows with runs-on
      labels:
        - self-hosted
        - kubernetes
      # Container resources
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "0.5"
          memory: "1Gi"
      # Use dockerd in the same container instead of a privileged sidecar container
      dockerdWithinRunnerContainer: true
      # Disable privileged Docker sidecar
      dockerEnabled: false
      # Use dind image
      image: summerwind/actions-runner-dind
