---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openseo-secrets
  namespace: openseo
spec:
  encryptedData:
    dataforseo-api-key: AgBC4PjXkx1kw33vqeTh2p9cOAEiQA7JkKTUzlizEep+38Rodk2UjNmJycGtYD1Agm2W61dRW3fZsKQJ7Y7ZXA0kBEb45mVVO4prfFaLpU/3cco8D7bPzZZ5sDrJk/tjmYtX+1jge2KEOOK77qCzuaX4OvmorgJwCQ+e6TjXHg7ltdH49a5JJ7gQPU43xc5W43Usb0EzeWCorp9GkTPEYdFcyCaGE0yPastYbVzCdFqeCWn5mkUZ+EHFMMu8qvwhIt1/Z0drUM5hLjiMJF2VhsbA++BPeYcUmrD4F1nKvp6gc6I/9EO3Z1e5RCuldoQRTYN5zT3Q8SiTf1QQtb0cE9h1uvo2UEPkBa7ZosAiP1rhABATrDxSMwMy5//eWvSiOfCZLobB52J8UFDgix6eLA1aMKq+dwGcD7iCca2XdZNsiV544ofAQPCIZm+NI/nYJYuP0KQ3AkeF5NcWy12bs2k+brlnA/bv64j3RdRrDJd8MsJ7SeHXxE4h0JNnp6nxaEoVt6nNRGsRfcfrE+V0RcmxHWQ4vbu1eXy7k6KV65VCHyTYoobEDq120yLa1lpDvsfQEhez+LCzDknDh2krWZsxltoFdO8sNNVS9UR8VFbF/9yVVWFtgkHLNj2+yFHtnx2qhFXpY8PJzARJksT0Qjc7t6PlEhRCeRh3vbCdfvIGQ+8s/6jP7wfnE5lsPKoqsPprAv+v2meWdSiOG0p6JzQls67NKQ+9xL34dhs8AV12sD8ZyBwhTy/BOJ6Wpg==
  template:
    metadata:
      creationTimestamp: null
      name: openseo-secrets
      namespace: openseo
    type: Opaque
