apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openseo-data
  namespace: openseo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
