apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postiz
  namespace: postiz
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`postiz.nmajor.net`)
      kind: Rule
      services:
        - name: postiz
          port: 80
      middlewares:
        - name: header-transform
          namespace: traefik
  tls: {}
