---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postiz-postgres-credentials
  namespace: postiz
spec:
  encryptedData:
    password: AgDCYhlCFG4TBpZyGBasiXoLqEu90xLfcJA1GgP+C6td2crNWAlMKbBrTvvqCq70mGw5GJXjt59wnbC2T73s1RcYe37mFaamECISugdJcGO2bAAZubz1eOTP2Z+UxTgoWcJrlYyULr85BKpK36um+4q8cnW7MZtxFjXZIQgsVQEZfd/vSUaYMAoEwVcOj2T/QKy44eiw+/OdscHuurzMKVItp+8bWJoL5EAHqBJngBV42omtw5gw1XIvnPM05RBRbD0uD/D0+dw5qSubMY/RO7fr4CrzX2Y9syJaymBFhzKUaxzoru4rkMvTcNU3yiIckPjDeUhr8jw2QldJ64I/jR/Kzl2xcgHuWnDfCiA+n1aWzhHOQT4BXRkxNbFQeGPl7KI3YwCQFTf6wW1exjWYYSkbJXcvZOSstkuPpS2s9AppqiJ8Gu8j2dBPmrKaHMr9+PCgFvJsCMs6vCb2fLIzKTQntZ18/9gAshkOOwhkhIL20ckmzOuhzg1ljV7xQBk1mCTI2c7KmKDrxFaVcR0JbtgfX+ovcA3lDm9FMM/HOLjUxdZgPpV/oWIFTCSbPlVuB4XyYUagGz6jI25tm6fAQPm1FLH1L5wVIt02sbE0qv9Q9VUY09KA4oIY1U33ixyYEmaNai3t5+c1+9iVaEQqCGgtw/A7eQBkA0zj+ctckRk/azt7HOUcPDkEFNErw7aqWuIRK7dneJjujF8Znp7ecNgG1ncd6s9guCnlPyZaKCqAyA==
    username: AgBfhXBOgwrPtDN2VkY4KkhMfRXKvt3QMNjiReFPfz/iDYc7it465hQxgzhNpoSMIuS32al89x4u5tYqozOK0zeQ4TSJg9MszM5dEm8K9jgrwexywVzNanyp4ow1mZyyeGS32KxT6oUUljiJ09WrNL8P4jW4CEul92doHoeIn6PrUQpICJZ2wV+fVJIJ58wnzBEqGvZCJXHIhI30jiiZUhZjb2VhmOy1w6+nz8eV0LyFm0flpAATYQRv7UGr8jKPQ238aBzZijHllx7WKh/272z+I38SlXXB6cCXSU+AQ6Vn4T21smHzAOObhNC/D4Y/Xz5DYUVELbgS3bEu8wQMC4KjFUVBqGOfQoRtLE0EeYajCtox2Cmo/F6G/9WOuPVrAfTN/VK2d71rYHABZrgONFVk2zvcxPohYIOkV0b2jV2Nix/tMA0+6q4PtUZc0vbmgPKK0+xhZRpmq5LGuk5ZslJC95xpjj1Xpg1MN3FnnagfPw6AASq9XDvgFDt+KXUcNJgaHN2znUYZd4/hJaU69xJzgh/BP5ZxHvNqPpao2mXMB0wIuB5Q9iZaQJEmiMeYO7xb2ILRVvTyg+sPmPpsOO2Z5RKHo/37AE4FiIDHy5E3HB64NisXOpmkPEuD0+yNOgIWBafinBHoFzXzU50QvjgDRfbbi+1Y4ohod5jJNNWoSw4Utl2UPCAC/A5hdrEgjrwmBSqatkc=
  template:
    metadata:
      creationTimestamp: null
      name: postiz-postgres-credentials
      namespace: postiz
    type: kubernetes.io/basic-auth
