apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-postgres
  namespace: postiz
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: longhorn-single-replica
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      secret:
        name: temporal-postgres-credentials
      postInitSQL:
        - CREATE DATABASE temporal_visibility OWNER temporal;
