apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: postiz
  labels:
    app: postiz
    component: temporal
spec:
  type: ClusterIP
  ports:
    - port: 7233
      targetPort: 7233
      protocol: TCP
      name: grpc
  selector:
    app: postiz
    component: temporal
