---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: temporal-postgres-credentials
  namespace: postiz
spec:
  encryptedData:
    password: AgAe8eX2tj2Xp4y68moPbcd4pW+j2gPyLM+9tsx+F6Ptni8xKTxwcpaRhjIChOwavjMFcklO37otQH9mToBP6buICCh22WojWkk6GeUEgKhq9V/rze+RQ67BztYdDpPoFChJp5eu33zo8igJ0S0PdImtqLVQ9cSm9HHYTVVOZxFL3Y3UAv4zM55ocMXh9WYSZI5GH9axp1bWs+Cw5uM/lSIpuIOgk7Zkp+5/X0YVLvJw0FjgtZR/zvLFNcdpmn+MHOlKKCznLGdlaiA19Wp1QoXXbrTJBSZ4+NAVzbXwz3jV0It1kyU3g8qZEU1h5EYdEHXGWuX0A53mTfAjjWZwkvCFfD9LvN7hOs2bTmcqGweNFmxBNsQFjz3YU69Q8NE4NvKQRuMS9S4I+eJ1ro36nrP+cjEtvdvdelqDNr4dRZB2Y8S/MqrrI2ScP4Mq2UGn06kkIL1HF1Oid6P7YKUE1WVf8GXMvDwNl/FzbgglPdWRh6JfbBKDEPbbIiObiUCTo4Z6GPw2oiVhNy1heZMlDZQuBHd4jB+k00WhN84g9ESJAyKFc2wZRsQ4Xd70ON8mMshLhpO5nG5vA0sZLtkv+QOxgWdUL91iafWD6XjJtpJBIzu1RCQwo+PpQfv5jYBeV4dn4vFlrOFZ6OHnm7bLO2axkkVUBsH6OjHyMaXl7euqrv/GqtebuZu2cAqFdlOTaRdRKOvqfuXZujNDZsJ1I+HUnzs21eYvmTpZa4qlChIdqg==
    username: AgCazyRnbSt8jV5t6tz/yOegAR1bQZcv+tZYfS1ZdVVpEnnFxTuINxRc0Ic6Xm92gGV4nSOknnFwAGRNlIby3pxdi91kgUM9JBKRuiW8TbvDuxRscMIdok19UtZG6DzsB/YfZCpl6uds5YZpqDZKkODmpSGGlM3ljBCQoaeYmrmoNn0TedQ5j3zaDe5F8TFCfUSCQ59yFlmuxND6/VxD5JTYftz0l2FgtFL1l0gFzKfnoVwM1Nm2FRBSdWLn3rtTfJEs2QjF3sdZCir8WN9Ns2hF09dL2fU/4IUCk0qUAwEwUhZvcdzjBLVqApQZBR0LXPHfqZ8/2Tl/gmc7Wjx0z0cmfOLfyDMVBMe0xtYhn3wzYVtdThbxgd+eHjRblx570T25zzMAukNrKbDJvdxNvZu4njY0GblnPYe3GFr/HOVUGHHqoANt6r486DpChd0B7VcaIUfyB31RS/WvvnBsa30jvhDse4wy5sYRgmmYPF2yoYQl2dnBCf3SW5zM05MvwYDKYaCxUlYlgJnUh9tEWTdw21PTJtXA2elGlWpUZHCbZSlj0ADUEQCagJnpZDXEeqzIAFyPuzsRlq3nDUEhczh7Wb9oCWrKj06zh4UYr/9rlqKxeVMhaQPfwKsndcZ/T3k7d2Iw10RPvEpyoVMTXnu823479L/LfQ0Jthy/Yoijk40ChWzBPWzV3mM7wtW0rWDxSMpUX0f/jg==
  template:
    metadata:
      creationTimestamp: null
      name: temporal-postgres-credentials
      namespace: postiz
    type: kubernetes.io/basic-auth
