apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamic-config
  namespace: postiz
data:
  dynamic-config.yaml: |
    limit.maxIDLength:
      - value: 255
        constraints: {}
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}
