apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-wildcard-tls
  namespace: coder
spec:
  secretName: coder-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - coder.nmajor.net
  - "*.coder.nmajor.net"