apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: coder
  namespace: coder
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`coder.nmajor.net`) || Host(`*.coder.nmajor.net`)
      kind: Rule
      services:
        - name: coder
          port: 80
  tls:
    secretName: coder-wildcard-tls