apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 15m
  timeout: 30m
  chart:
    spec:
      chart: coder
      version: "2.26.0"
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    remediation:
      retries: 3
    timeout: 30m
  values:
    coder:
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: coder-postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coder-postgres-credentials
              key: password
        - name: CODER_PG_CONNECTION_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@coder-postgres-rw:5432/coder?sslmode=require"
        - name: CODER_ACCESS_URL
          value: "https://coder.nmajor.net"
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.nmajor.dev"
        - name: CODER_DERP_SERVER_ENABLE
          value: "true"

    service:
      type: ClusterIP
      sessionAffinity: None

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

    # Liveness and readiness probes
    livenessProbe:
      httpGet:
        path: /api/v2/buildinfo
        port: http
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5

    readinessProbe:
      httpGet:
        path: /api/v2/buildinfo
        port: http
      initialDelaySeconds: 90
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 10