apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: coder
      version: "2.26.0"
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-postgres-credentials
              key: uri
        - name: CODER_ACCESS_URL
          value: "https://coder.nmajor.net"
        - name: CODER_WILDCARD_ACCESS_URL
          value: "*.coder.nmajor.net"
        - name: CODER_DERP_SERVER_ENABLE
          value: "true"

    service:
      type: ClusterIP
      sessionAffinity: None

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn-single-replica

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000

    # Liveness and readiness probes
    livenessProbe:
      httpGet:
        path: /api/v2/buildinfo
        port: http
      initialDelaySeconds: 60
      periodSeconds: 30

    readinessProbe:
      httpGet:
        path: /api/v2/buildinfo
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10