---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-secrets
  namespace: coder-workspaces
spec:
  encryptedData:
    GITHUB_USER_EMAIL: AgCaOvK2KXTMcQYllfKMUDNZ9CXtmZx0urRW1B6OJW2LljKpESg/G/a4eRBbUUQM2/LoTRqKlLfAfZsvoMJ18+7q2ygJQFHKt/k2SfB2u8HdTsNCcRrkRL/pYm9nAspEWeMXuTUG9D5waMXVIflPnHaRfmG5APguWMGO1tF1OxOiVodyNWJPUNyq3ak3KR4zO0jFaUmXzWXk6AvGVLlM91zb9kvjMahph34Fm2E5sjWlmIvMSVGmd3FQic7w/0S1ct3Se0gk9LInYFKNoV5zzthr371EC7jyHTXrHiVXDo1HX3JzhWRjUMd7o4IPpW361BJIlYts7xxXXCaHwVfRgdzsoFvCIxv0Lycjf6cHW/XU5J4SjP6VoTjE3I1QX3pZ8SyZv/dnyxSbnn7r+Glh8jasvcWBhl/jQbx/DSpNAMqDWCNep/1mUwnq3ASJMNHnU+AEE/W1ItRpEzdLoBLNUTivY1Zr8mm9NRbp0rgnCXvFDX+XndoTNirxXFpHAd+6EVBkiyMZOPZV0XHH1qHXrGlpkl8gc14OsKJEwxi1Bu2kRYZjE21FObvRuAzOHxwqUfJq4yneb5vFjsFRlvVEPHH6UCgzT6a+FS7t0VyxCobI5DjKSkvlCA+zZ7QZJJl+Tsydtj0GXEpxv3cDpv3xXGf6L8SPWEDGxCK9QyV1B/7E5KcBc3ksq5sU7Zk0RJYcb3gqSW7kCJ2aL9xFlY2v1PA=
    GITHUB_USER_NAME: AgBcF/kqIIX2Ux78DO5249lBIegUZ3WFl5UGMBiF8RK4tYNR0eXO8d8OEz1hKKegsnJPIBTL8gEOHBx2O0BasSc6kfZNHTpOxWzEEIeJlJ7tJjugeFhyRGmhABVlCxnITBgStmzo40TinLwPwGsiF4AtBUzbNaGFnMikfIf7GFrnFZM2lY4+Mv4jFDmQeL9e0+LN/x5Z5CMyKH6H8CToU8Jvu90FSws3AKbkU9A8oTcdlsSUOYVS5ARGmBTvODQsF4NdGp1ZxTXGDaZG2CqdzUnJZYGVw7XTja74HYLQTfnn114vI1IQ6lSzRhx1PZ538K9opG3X83vsl8rHtEGlT3s4HN7IQcffUGA5i4WOjdjih/RIIZRKIGr2Wtqa1VQ/jQ2JTGW2FeOMe8fU/5y5ERx+xdESfPWTAaFgVc54XR7NTaAHa5yPDdk39RGqyp+7DFspTqdszlgsvMUZGMZFwVK+tfCaukJv2nfpgrlgjEObTaP0k3+51Svl4WLqdZgDx0BMNrAk7PioE5IjsFmud1SoCgXuBi2q7JQHqcgfwQa0kM6WllXZxHN0AWV3b7JMqmiAT6faNSTFNneyitC42P/YxFkzzi4g6DVYXXCIStn7j3ZW/D1RgSBjPG1940k3CfoA7AFVdt5K0JyTLwv9wAK8SCxz2B0bH+NYXVkYkqXJGTPMg1pqm2G1DuxEMOoZ84Pt0HU8XDY=
  template:
    metadata:
      creationTimestamp: null
      name: workspace-secrets
      namespace: coder-workspaces
    type: Opaque
