apiVersion: v1
kind: Service
metadata:
  name: peek
  namespace: peek
  labels:
    app.kubernetes.io/name: peek
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: peek
  ports:
    - name: http
      port: 7700
      targetPort: http
      protocol: TCP
