apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo
  namespace: echo
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{any:.+}`)
      kind: Rule
      services:
        - name: echo
          port: 80
