apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 5Gi
