apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bookstack
  namespace: bookstack
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bookstack.nmajor.net`)
      kind: Rule
      middlewares:
        - name: header-transform
          namespace: traefik
      services:
        - name: bookstack
          port: 80
  tls: {}
