apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bookstack-secrets.sealed.yaml
  - mariadb-pvc.yaml
  - bookstack-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
