apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-database-backups
  namespace: n8n
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
