apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.nmajor.net`)
      kind: Rule
      services:
        - name: n8n
          port: 80
      middlewares:
        - name: oauth2-auth
          namespace: traefik
        - name: header-transform
          namespace: traefik
  tls: {}
