apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.hlkube.local`) || Host(`n8n.nmajor.net`)
      kind: Rule
      middlewares:
        - name: oauth2-auth
          namespace: traefik
      services:
        - name: n8n
          port: 80
