apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "n8n-session"
    traefik.ingress.kubernetes.io/session-cookie-secure: "true"
    traefik.ingress.kubernetes.io/session-cookie-httponly: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.nmajor.net`)
      kind: Rule
      services:
        - name: n8n
          port: 80
      middlewares:
        # - name: oauth2-auth
        #   namespace: traefik
        - name: header-transform
          namespace: traefik
  tls: {}
