apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-credentials.sealed.yaml
  - n8n-secrets.sealed.yaml
  - valkey-auth.sealed.yaml
  - postgres-cluster.yaml
  - postgres-pooler.yaml
  - valkey-release.yaml
  - main-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - ingress.yaml
