---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgBQXvYiVzRRm93CK2XEKk4T3Yueg/1RoATGmcd93Hk0s5z2Wc8VndeCcizs2HDRLZBxbJNwUm//i7jZRV4A5j9dHZ3FMqQPVC69eVTpa17pDGYk/5Wcki8Q3XKJttEBFFb0JPnS0XqqOWEIixMViAAWRfes6DJkv7O/Wo3tLi0KhO+YEnEdGnIEPmNdh2GfytidKk7ZR+GUsK/Dko30Guxc3wNSZ2yfgZYVhMZO2Fnqmn1Aes8W75xEAuOy/YGECDYKN7z1UobEz5khv23WoohrOWWNZJ2FhW2GRKvp/LaXPYNcIk7cZxxSI4Jh/HjPyd+OUcJdWq5gvrWJWr0KJstsddyzqS/YSAFLs53e3daM9sGjIbFoD7ayrBm66OCxm1JllyJ2fF/1Flxa+PSv1tZzYeMqmt93Ce4jRLMn+UjE96C1xgSLCP8NwF1ozC2DSocVeohvm7PqYlcZHRAmaPDF548lXyC3tUoWSLQ0tjqNmT5iGQzjOH1esC8tAxK4udVBCZFOO2JRHFuPDtuFJrg266JS+hgyVJkl0zvIx3FGCtiWNyJyPi+XJ2M8+FvxKuyu4NdKqKfwx6hHfJtGdRne920cwgsjPyEHPtxNCn+x5ObjU7S8yoeVuyBYcWeWyBW/jTHRuiz142J2jP98H/v7hTnO+CUWfOobJeMRCg4Gruym5Hg19vq1grgQESeCUyW8TEZh30lCy09JiLbbVemEp1M+nbpX1NQ8yJuphlwCYg==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
    type: Opaque
