---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgB/pNZBW+ovXfLlb+hUcUOeBBi529NJPU+9k1bAqm08ZLfnmmQhA3j0tCmeWNRIDEAkgL6z00SJqsgepDEcAZxZHZVhdRej/qN4UGddtMLaL3J0VcNaUIZ5NpAhQQoGz6gLC7+XYEriFUiKRPgkjGRbgq1nlNWNZaSYGLb7o0bKaEKuKrOrNEq+Oa/A2mJs6M0I2HK4olloebjrlTYkWkvaSVc7Qy0CxmLrl4aDcvOMOc8TJXeiAqGCdojPlbkHubuOKxQrNLFsq4XHoWwoLleS0LogYlwaEBTaou+uQRcmXp71WGYCkI4Iud+Tb7ztjeasDX2eAazx9zKdBvUTffT1XGrFcYnK9v+HHxOvDVAKBpVwNKr1wmTX9Y3W/lffmkaBdAz3jYIV8p9oVnZkcWiFBe6cmiC9LtQCJjvcDNZVqRYbTDZC+K1avMxX4gPDoalpPUbl5hDl1O9htdeVEWPG7ipMbiTraggYKLEZ9lGMiNAhr0Udl6gS+IzqE2g3HDNgmAHs3MtPhqohrNtKIFhVt6dQaVi7GBkka4c9/RvosX9Xe6Yv6xwvOJWx/I+GmUGAVgZkwTKpRC6VttNA48by51zurLvK3hm+PmpeTtcnfnbt5UcttgcLz42+X6UwOHWT+7ynYoVVd+ZuEocn5abnxVttwb18LZrTV7kyy423y1kmJHruyPmAAiTSDdm0+AuPg4cv4mM9Rtevcw+TTdT9o4oZgK0PJevBiQJg3K69uQ==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
    type: Opaque
