---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    encryption_key: AgClxlrKTjGZ4WbHfIJEq+6jLNbNU3sHnLNHugms9wv/dPnltnwuGTYvEL4qY9oS0FxQ9rlLvu3eCyBz6nxHoe4TumNiiMJ1yDCAfKq7dluTI3dnL2x3RoQgs7JZuqGTTyulupl/vr8dCHyBP3ev+oqrEnbOpvA/ztBqJFaYyH6NSt2G4Yv1KJuL7s6JkuW1JQRqGz/n5Si21KB8+55LAqKiOESDXg67eLXQ3uNnBFP5Oo7lMKIYay9m79hWNWm5mVHIovGEK3Hw1i0bwZwHnIwn3ZJQ81SdCUzJO6GMlmYdoVmWKB+4RzFb2m8kVhrLy+czQFxX+pOq/t9OTstH+PtbJvLVz9KzfDw+9nLq6WLqyUYpGcPvpqOqmHzfkBdmwOw4pg/FZvw3K/9VagNuSa6DPan7fUXANZfBGd+0fjsMVBEry0bdRwl0Qtv546GBSq2xSvjYoBb7+1Fr5+SCxvMLdpOeZY1zz5vtpdDSD84JNJSDJf0kz3kM8++3tbEm0gNnPG6asvNrHEyzQS9XHLUVzCHnKv2amu705H9Nf8lwj7EZJbXreL1gjXf2pVSCNxY82v/bBjUYEEgAsy+jWzVq9Omc3kgIgNXZaJgbeCau/vOJQruUk2xqu+3+p/Hvx7bnVLfhrqtK//iyKhh5CwgJ4J+Zez4PiU2DCWnslJWlIpS0eGpg9s2jdPODn3Z3MGaBkwQw370SAEaBJ3pb9Ts3gQwX98abM0pwtmWrLKyDfA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secrets
      namespace: n8n
    type: Opaque
