apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: n8n
    namespace: flux-system
  values:
    # Main n8n instances configuration
    main:
      replicaCount: 2
      config:
        n8n:
          hide_usage_page: true
        db:
          type: postgresdb
          postgresdb:
            host: n8n-postgres-pooler.n8n.svc.cluster.local
            port: 5432
            database: n8n
            user: n8n
        # Redis/Valkey configuration for queue management and webhooks
        redis:
          host: n8n-valkey-master
          port: 6379

      # Reference sealed secrets via extraEnv
      extraEnv:
        N8N_ENCRYPTION_KEY:
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: encryption_key
        DB_POSTGRESDB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: n8n-postgres-credentials
              key: password

      # Resources for main instances
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 2Gi

      # Persistent storage
      persistence:
        enabled: true
        size: 20Gi
        storageClass: longhorn-single-replica

      # Service configuration
      service:
        type: ClusterIP
        port: 80

    # Worker configuration for distributed job processing
    worker:
      enabled: true
      replicaCount: 2

      # Reference sealed secrets via extraEnv
      extraEnv:
        N8N_ENCRYPTION_KEY:
          valueFrom:
            secretKeyRef:
              name: n8n-secrets
              key: encryption_key
        DB_POSTGRESDB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: n8n-postgres-credentials
              key: password

      # Resources for worker instances
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

      # Worker persistence
      persistence:
        enabled: true
        size: 10Gi
        storageClass: longhorn-single-replica

    # Webhook configuration - re-enabled with proper Redis backend
    webhook:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi

    # Valkey/Redis configuration for queue management and webhooks
    valkey:
      enabled: true
      architecture: standalone
      auth:
        enabled: false # Simplify auth for internal use
      primary:
        persistence:
          enabled: true
          size: 2Gi
          storageClass: longhorn-single-replica
