apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-valkey
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: valkey
      version: "1.0.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Authentication configuration
    auth:
      enabled: true
      password: "" # Will be set via existingSecret
      existingSecret: n8n-valkey-auth
      existingSecretPasswordKey: password

    # Architecture - standalone for simplicity
    architecture: standalone

    # Master/Primary configuration
    master:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: longhorn-single-replica

      # Resource limits
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

    # Metrics configuration
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    # Network policy
    networkPolicy:
      enabled: false

    # Service configuration
    service:
      type: ClusterIP
      ports:
        valkey: 6379
