apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-diskpools
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/openebs-diskpools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
