---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chatwoot-secrets
  namespace: chatwoot
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBBKS4JJeec4NT4o/til19DWT/bVK+7HzK3nL9R2luVOQW67EEeJdBKlteBAkd3RN1PQHVGERXGSC/ISxw0PTZSLI94kX63B6NMQ2FjCZ9Z6QRbvwsBmTZUwQk9GcugqMHcEdlRFcB31MqLzu8H7e4tfnIxbJqDm7Qm8wXig4vnYBRmuLRyrhvKIvkev2ih+JMqiSOBLpAcMXXA0fX7vfCV9MypKqYXPfBxTWZDasMug5LC19k4EguIMMk+lylFnkVSmA+nOo1Z/fWe94J+3dg4BxddDhKYqtP1ifMmfEWTDX6TPxXmYGTPco+mqDVRIXZWk8Zbqn1x/yUW8LUDF5+J+9zh/E+DYWUxWX1oEKhoT1dBlejSiOALx3XJ/o+VG9qwXDgdU/mFtLv6CTwF+cP3GBvUqftxPKsPBQzX02B3a9QQ4DlrfFHXEAbAEVO4jlAlgNvc51PjIzsIN/feGUh4buCYmQdrZa1aqgq8gYm6fwm8fiouA4FSaw6vHWE8t/GuNRz+Iyxw54ezFRaSRvGyfXRyp2oiMGHJqOyqZMJGYBpLVw1F8fHgZoLdPDFEu7E6XMydnq0TdOvnjEpZ/8RTpgij1CMH+KaTBEcKfglVFkLySOL2Dk0pIlFr5KSy7HQulesab0TY8GWWnz0VqaVRC17QtSjcYKb6ltwN++gMD+i+n9GCB9lNIPIMLHz7vruDgvMlnUdQyxFHwD3xCBmzfZf4XyjZbreqieRP3NdJGfJkNTzPf7h47SIJm+tnBhkpdrhkcoOnskjoH0mSpR5SaqeR/0xozAbmusv/8hNcMbqQIlYS1rGxyLcgMb1MBIHT8Tjl1eDiHglrfr+IP1WZeVZEIqEo1qFEdVbsoIHpFg==
  template:
    metadata:
      creationTimestamp: null
      name: chatwoot-secrets
      namespace: chatwoot
    type: Opaque
