apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: chatwoot
  namespace: chatwoot
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chatwoot.nmajor.net`)
      kind: Rule
      middlewares:
        - name: header-transform
          namespace: traefik
      services:
        - name: chatwoot
          port: 80
  tls: {}

