---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chatwoot-postgres-credentials
  namespace: chatwoot
spec:
  encryptedData:
    password: AgC4lpMW4DBd8UzH2eDb8Ha/JFr2G4EgP2qVOfJ3vqT8I+8jOg0nygASn8CeWHN5FJ6gzaar+ZnQufNsCHp1eXls1kTs8Ippkk88BkCzFys44V+O5OZuZzQOEOSM16YDnFX6XYrj48iTulpXCwgZDbeFn9FVk56kQM7mfKJ4TIhAfz/7zH/Yl/JFVDtKpYwc4vPEKUXIflRSQ5LZdxjRWxHVEk1LakeDUNG4BJnopArHSqvekRlUl1eNTnsaqUqQK5+uB8kML2NQHkoIcTwGPe8eF0cJVNcV4UFgLfa9+hrlyyXJBHf++wwDnJkOHu9fKG5Ccw46H1I7fv5Nyq1YM997npD0TTGbsnWH3+HJrqLDfN3XLX7/woiPNQO+kkcEquHZDvkPw6ogDoxR0vtwyM8F5Ow/eBH/dJu/ZEsXmsHwll+Zz6NYZSM5Ojvql6S+KgTxEZLClrXAoCR8PQVe+rUYSpiq5lIn06bUQfQVKBz5nK3Cb5GdttzYHmTovpo0Lq63ZQGcmazM4DLeOX/C7O34PBk2wdCQ9Iix9/jB3MHjWeY1KjNbjws3zAJGAWByBFHBxqi62DpTy7F+hZvo/IJujYwnqn7JCGp6P1xJal9u0P8mBewwdSXU3cRdFKyx1SN7OjExXOOrws4DwPla/YkSUdgq6Ps7TnD7O27lzJwBevmQF3dHxV5cD/R24oiFMAld0x/dyW6ZKCxxfB0mwSCm9C16ST/hyH6ZS5NlmZXLhqw78FcwhfJk0vsAR+BkjYvxg5d61W8mhZQW1tRrqPvo
    username: AgBHhpXXCTDCtiZAJfs01ft2FYc29lzNMYFybKrYrkE5jbNc+PKkn82E0pFJbcdi0BqXl2oRJZ2MLlDBFv45glQwACN2tEW94KYX0MrSvPqK2dcscXnofdmH4GOR2ymCfYGtKVge0KBLRn6s2X2l3dNk+iYxfSjNgMGjWBIB0/B8iucnGGRSHuBKJ8x9afvzP2+OTz4F0HPaLAbZRTb7bV+XhOpl5V+m4uwbmB+b3HqMjWDcm5W/Lmyb0Sqfa9zvarCf+vSlDu0UpuIe+hrsZGrC9O+qRsV9/pnZ4CPt6yixEnrq6sh47BUCzrnB7AGfCqL9Fz0g5hRfv6tXMcM9vbVGGBXKIC+KfuZVyfPMflvntoCp9+baET9I3UtQwm8W2NcIrQhPt+sYxA7qSx5IMSmk956QRxXWZQe8U1Xvj/G73qO6k+u2nJQzQOFYYiFUmprAjDmEnpJQhvlF06t0d4d/pFekKCm4qwm6BV7usEeRW+rm47hpdCaSV2vZOOwk6vOe3J6AgoNFopWjqXsGhJWwNrGpInvMHne/pAZ3YHkVKWXr44UbuYQpqGG7DJuDpiMKavzWpKEgx2Dww6xRAxpdUXp6WpeYsVJXxcPJzdDylGG1wvUsROQ/F28GMfBslcEwdv2AW5+V15t6UrEF296GJ0okagQszKOD7/pX6qoU82AyBcUh+YQRj72bfZlxTGbz1e+g0iGuhA==
  template:
    metadata:
      creationTimestamp: null
      name: chatwoot-postgres-credentials
      namespace: chatwoot
    type: kubernetes.io/basic-auth
