---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: healthchecks-secrets
  namespace: healthchecks
spec:
  encryptedData:
    secret-key: AgBnUykGYeQ/f29fRzuhM9lVbsJfhW82FD3/0y2EFyzt2X4/ZixgqbI1bqDLaIdqKuzB9HdeYDU8RXddHMUgCFvPE/3pnOtBJjftCCGovrNYZAvk0Uwm9XKMCKhh0HSkQaBYdDfokZNXCCCNRDI/AK8QZ0yweDgUnh/Ei77EFTSjD1DgEvD7I5DY6eon0GtEstALrBIVU5yBDQ0qsqYnalnuK94gkNhbvHC5iXn0jN6PCpN321VT/ybH6X3/NxFsUDLBgCrTI0NDCkhaOILlBH3FslU6Gna8yXlqAhgNf31FIRtSm9cJpWTe7bMD32qHx99GAZl6o6wdzKx/0zjhLyUOwfXXdhwK4YIaap2U1YE2PYqa1tWzsBYG7GV9makUUiK6bwfEZZFFzRFbye0W1bPxi+z+/xuH+Oi3ozFd/oP36m8AanyMca7sAlDZ1zRX3lhRXd47bT26KmZ77wQOz9Pc6o5lASEEXkGfV1mnTniY8rP+c3JbH6d33ieLYzLDYHGVcTzkRzvem56aRiW3o73/Mo8bGuA3f5y52q2616//13flt4up3LP/9HDO0KRhKW5EypXhGhGOOz8q7g5XEyX44My4ocO/pxf1KiV1rKU2txQXH1NNOcowsu3glxbcP0o8rT9nduPQshB21J7ryaGQMD0K1Q+jeNXl0ysMUlDJptunxKBzSll+IdHwwUIiiSu7RpMU4/wuQdvcrEOOtMuLXEglxIL18EYiwLAdYiFHvzqVVK2XWrt+QO6chQ30cA7foJWLROnnitVIGOsG510z7+fTeQQLqQ3aPE/nNF5vWtNnqpfk7SRXRQ==
  template:
    metadata:
      creationTimestamp: null
      name: healthchecks-secrets
      namespace: healthchecks
