---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: healthchecks-postgres-credentials
  namespace: healthchecks
spec:
  encryptedData:
    password: AgAJgKxvBQORzwjLByvjMN/TofADv9i65FGfnW75NAxziVm+p2stYipubiaUbmP+29f6v/RK7iVLenpo785K5go8jCGs565vjYZFHq1RKxDKrBUPAHWH7O4UUQEaEfX69XC+Inj5vOICHpqy+t33hSxx6pr1AegWOtykM8XI5QBcpAAea3h9loSBy1aPVgPMEJDqo8OpgKw8M2LEbwZsaa7W78kIjHpLRISr6ZRvEJJHngis48ZrqZbDkrcN9jhdiQ2xqlmRuCca1kX0zLsYmSA5CSD8UNj2EeYGxpm4RaUVhprmnvlQrYb5XcFiGa8T4LqvPGjBXyc9j2lwiqKnfQi8mCOrFX/PSY54ooV67N6qNO//7kOjC+B/NVwt/JlM+z9PtWDq2ReCtB0IX8SoS0RgPeXl3aK63NltgXoqN/sVpFgcw2xaBCNoV0L61tVBNpLd5ciGFp+xmjyRz/d4jCyfLm9gTytlACGita1M8MtcmMgZRp1xzghbepVXKbOh6+IPjqVM4laNBbFoMtTRulBHW0w9XROQBZ4Hb3Pb6NDmGrRCiUK93zWflfX8wIpP29UXhoUSzbF6vCC7a65ka8DxsoygfIkPQY29R//dUhz3Yu0iW7v/rOmlm+yhyYrjupRnAylALFhPF/UJHtACyJVEm5uDbDyQAHxbRwl9k0E+Fs2u+LwxQx4uOxovJ/OWU729V096njjsV9SG3SmlDVddxAZJGlXs/3N5gggGYl0JFE21avwC1aW6pnxaA6X7y0Y=
    username: AgCKD1a8i96lijmUnqkE2dyiUQ6T1q1XikjhOKmJ7TP0TD3lt2NiF5VXLb/6mzMbxYSRFT/Nr0zlXa4E4ZzozUik2QAN8Qr5Us4aDOTwU+QZGGsMYM0BlJ2GyPg9EOCO78CKKijmN/xD69H3+G+JeDv0MmE//sDk3SZ7SyygqKmRbKytF41P0Pri0JrgpcxqvhSs5h+kgUAEpgZKYFFpJ5D3jYvtPriGZmHRGpY9M0626ipAGK0XU4l8Vhn/Gbq8gaEHyeMsJi57QRyYiJ/E7afsrOS2DTv3cXuc9/VweRqdjV4VC43cQm3BJ3YFLr9XtL7MbD+4tAgwa3IVh60sgv/bkUKopCg9Qq/WaRBSu6xP8ilXdYJO6e9wIr6q1NHMCiMUr9EpAlR7FofetnRk+TIhUr5eK5Lv/hPiCWIUveP5Nv1ylKt8qPmM0+rfXIPadSZUrZ4rfYLLt3gqw/Q/MGIdH9fDL8rgwBK8ola+AKdxvoXFEbECczYQZl4IL2CBTGOGmyom8E58MGldChyclelvrJAmsdOzrYIkC/uNkjXYNIYq+sWclNLKRQtPtzQXxohe2GWs8wV/J0lkvWQKp3IbaYQ47tk+b4Xvaak4Wyf6oeao4cRovGyEO9BD5/KL6fHnn2a6BegyZluZTLhsy8gZiM9RucdhQvN/lqCYiiZUEkHgXYbdmjCpWQf28YHod5bauamKb7L8vdj1Lls=
  template:
    metadata:
      creationTimestamp: null
      name: healthchecks-postgres-credentials
      namespace: healthchecks
