apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rybbit-database-backups
  namespace: rybbit
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
