apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rybbit
  namespace: rybbit
spec:
  interval: 15m
  timeout: 30m
  chart:
    spec:
      chart: rybbit
      version: "0.4.23"
      sourceRef:
        kind: HelmRepository
        name: rybbit
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    remediation:
      retries: 3
    timeout: 30m
  # Merge sensitive values from sealed secret
  valuesFrom:
    - kind: Secret
      name: rybbit-helm-values
      valuesKey: values.yaml
  values:
    # Allow non-standard images (Bitnami Docker Hub deprecated, using ECR)
    global:
      security:
        allowInsecureImages: true

    # Backend configuration
    backend:
      enabled: true
      replicaCount: 1
      image:
        repository: ghcr.io/rybbit-io/rybbit-backend
        tag: latest
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      betterSecret:
        secretName: rybbit-secrets
        authKey: better_auth_secret
      env:
        BASE_URL: https://rybbit.nmajor.net
        DISABLE_SIGNUP: "true"

    # Client (frontend) configuration
    client:
      enabled: true
      replicaCount: 1
      image:
        repository: ghcr.io/rybbit-io/rybbit-client
        tag: latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
      env:
        NEXT_PUBLIC_BACKEND_URL: https://rybbit.nmajor.net
        NEXT_PUBLIC_DISABLE_SIGNUP: "true"

    # PostgreSQL subchart (managed by Helm)
    postgresql:
      enabled: true
      image:
        registry: public.ecr.aws
        repository: bitnami/postgresql
        tag: latest
      auth:
        username: rybbit
        database: rybbit
        # Fix: Tell rybbit chart to read 'password' key (app user) instead of 'postgres-password' (superuser)
        secretKeys:
          adminPasswordKey: password
      volumePermissions:
        enabled: true
        image:
          registry: public.ecr.aws
          repository: bitnami/os-shell
          tag: latest
      primary:
        persistence:
          enabled: true
          size: 10Gi
          storageClass: longhorn

    # ClickHouse subchart
    clickhouse:
      enabled: true
      shards: 1
      replicaCount: 1
      image:
        registry: public.ecr.aws
        repository: bitnami/clickhouse
        tag: latest
      auth:
        username: default
        # password injected via valuesFrom
      keeper:
        enabled: false
      persistence:
        enabled: true
        size: 40Gi
        storageClass: longhorn
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi

    # Disable built-in ingress (we use Traefik IngressRoute)
    ingress:
      api:
        enabled: false
      client:
        enabled: false
