---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rybbit-secrets
  namespace: rybbit
spec:
  encryptedData:
    better_auth_secret: AgCyryXpH9rppOz0AWX2KYXddXagPwtm3akiEFhN2MOflU7VMvKfdHLzoIGkls8/2ar2hdgQbEU5gEGz523Pd6jnHvzmu40jI8cg8Hrg0eOjJlXWM0Lbia5HjDAeBXpcRlgxwP1PqNYjXtKvGrG8HvCU2PCMxQq/nTRonUjaEVFxw/A4ZDoSnqTS5G1BLafNH7T3yjbReLuLONTsxgZt1hT1uCcqg84iRmSDcateAlaO9fxNbhiouifP02GlW5qUzFBoC6GZXvmzdN4ytTuI/jkpoIEpJEtmqgV7Uid/WvL+JUrVyb9CRnDR6jAd7WDjx4laOpbaR2ERUXHAEc6/Os8YKy4yjoaU8nXSo2OMSA7CFlHY3OW33Zv1kA/aq7ISrs3X8+ObuhUuJaSxtuS2PxdOQgeBGSaszAun+kpvknpPGo7BIh19fytzJqGKeML/lxtnN4nwIeAmmkMJhTEv7svzOT1goEjW+54fQzSuWrqJAbnC7IrDEigbbL6aQw3V21pCJ6gMrkJCYuv1EPNHcJVjJIX0rQejQNzzLMVh1LQOUE4Y/zcwsLPbdyaOd+UMSxPw7RP87WK9qxODYHcJ3OUGG2gSZMBBKBCi08zrOu6EbnquQGh2MyWp9G1bB7dxiHKZeWSwbBZzu+uu+BdtmBCwEnsxhOxnijwdtzv6vUwK4ydkIE8ZJAQXtYgXLEBfqgcoULFKULUSV6ADN3twfkg99w1ifGFBgzLwoB+rQm29Wk9YHA9Fpe5k9+Pu
  template:
    metadata:
      creationTimestamp: null
      name: rybbit-secrets
      namespace: rybbit
    type: Opaque
